### 1. Count Vectorizer

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = ["Grow your data science skills by competing in our exciting competitions."]

In [5]:
cvect = CountVectorizer()
cvect.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.int64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': None,
 'min_df': 1,
 'ngram_range': (1, 1),
 'preprocessor': None,
 'stop_words': None,
 'strip_accents': None,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'vocabulary': None}

In [6]:
output = cvect.fit_transform(corpus)
output

<1x11 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [7]:
output.toarray()

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [8]:
cvect.vocabulary_

{'grow': 5,
 'your': 10,
 'data': 3,
 'science': 8,
 'skills': 9,
 'by': 0,
 'competing': 1,
 'in': 6,
 'our': 7,
 'exciting': 4,
 'competitions': 2}

- 불용어(Stopwords) 제거

In [9]:
# 자체 제거
cvect = CountVectorizer(stop_words = ['by','in'])
print(cvect.fit_transform(corpus).toarray())
print(cvect.vocabulary_)

[[1 1 1 1 1 1 1 1 1]]
{'grow': 4, 'your': 8, 'data': 2, 'science': 6, 'skills': 7, 'competing': 0, 'our': 5, 'exciting': 3, 'competitions': 1}


In [10]:
# Scikit-Learn에서 제공하는 불용어 사용
cvect = CountVectorizer(stop_words='english')
print(cvect.fit_transform(corpus).toarray())
print(cvect.vocabulary_)

[[1 1 1 1 1 1 1]]
{'grow': 4, 'data': 2, 'science': 5, 'skills': 6, 'competing': 0, 'exciting': 3, 'competitions': 1}


In [12]:
!pip install nltk

     |████████████████████████████████| 1.5 MB 7.2 MB/s eta 0:00:01
     |████████████████████████████████| 279 kB 25.4 MB/s eta 0:00:01
     |████████████████████████████████| 97 kB 25.6 MB/s eta 0:00:011


In [14]:
# 최초로 nltk 작업을 한 경우에는 punkt, stopwords 모듈 다운로드
import nltk
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [11]:
# NLTK에서 제공하는 불용어 사용
from nltk.corpus import stopwords
sw = stopwords.words('english')
len(sw), type(sw)

(179, list)

In [12]:
cvect = CountVectorizer(stop_words=sw)
print(cvect.fit_transform(corpus).toarray())
print(cvect.vocabulary_)

[[1 1 1 1 1 1 1]]
{'grow': 4, 'data': 2, 'science': 5, 'skills': 6, 'competing': 0, 'exciting': 3, 'competitions': 1}


- 인덱스에 해당하는 단어는 무엇인지 알려주는 함수

In [14]:
# 딕셔너리 반복문
voca = cvect.vocabulary_
for n in voca:
    print(n, voca[n])


grow 4
data 2
science 5
skills 6
competing 0
exciting 3
competitions 1


In [15]:
for key, value in voca.items():
    print(key, value)

grow 4
data 2
science 5
skills 6
competing 0
exciting 3
competitions 1


In [26]:
voca.values()

dict_values([4, 2, 5, 6, 0, 3, 1])

In [30]:
def get_word(index, voca):
    for key in voca:
      if voca[key] == index:
        return key

get_word(5, cvect.vocabulary_)

'science'

In [31]:
voca = cvect.vocabulary_

def get_word(index, voca):
    for key, value in voca.items():
        if value == index:
            return key
get_word(5, cvect.vocabulary_)

'science'

- N - gram

In [32]:
text = [ 'I work at google.']
cvect = CountVectorizer(ngram_range=(1,2))
print(cvect.fit_transform(text).toarray())
print(cvect.vocabulary_)

[[1 1 1 1 1]]
{'work': 3, 'at': 0, 'google': 2, 'work at': 4, 'at google': 1}


In [34]:
text = [  'I work at google.', 'I google at work.']
cvect = CountVectorizer(ngram_range=(1,2))
print(cvect.fit_transform(text).toarray())
print(cvect.vocabulary_)

[[1 1 0 1 0 1 1]
 [1 0 1 1 1 1 0]]
{'work': 5, 'at': 0, 'google': 3, 'work at': 6, 'at google': 1, 'google at': 4, 'at work': 2}


### 2. TF-IDF Vectorizer

In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = ['you know I want yout love','I like you', 'what should I do']

In [36]:
cvect = CountVectorizer()
print(cvect.fit_transform(corpus).toarray())
print(cvect.vocabulary_)

[[0 1 0 1 0 1 0 1 1]
 [0 0 1 0 0 0 0 1 0]
 [1 0 0 0 1 0 1 0 0]]
{'you': 7, 'know': 1, 'want': 5, 'yout': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


In [37]:
tvect = TfidfVectorizer()
print(tvect.fit_transform(corpus).toarray())
print(tvect.vocabulary_)

[[0.         0.46735098 0.         0.46735098 0.         0.46735098
  0.         0.35543247 0.46735098]
 [0.         0.         0.79596054 0.         0.         0.
  0.         0.60534851 0.        ]
 [0.57735027 0.         0.         0.         0.57735027 0.
  0.57735027 0.         0.        ]]
{'you': 7, 'know': 1, 'want': 5, 'yout': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


In [38]:
tvect = TfidfVectorizer(stop_words='english', ngram_range=(1,2))
print(tvect.fit_transform(corpus).toarray())
print(tvect.vocabulary_)

[[0.37796447 0.37796447 0.         0.37796447 0.37796447 0.37796447
  0.37796447 0.37796447]
 [0.         0.         1.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]]
{'know': 0, 'want': 4, 'yout': 6, 'love': 3, 'know want': 1, 'want yout': 5, 'yout love': 7, 'like': 2}
