# Numpy

In [2]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
a.ndim, a.size, a.dtype, a.shape
# ndim : 차원
# size : element의 개수

(2, 6, dtype('int64'), (2, 3))

In [4]:
a.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

- indexing, slicing

In [6]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# 5 - 두번째 행, 두번째 열
a[1,1]

5

In [9]:
# 행 슬라이싱, 열 슬라이싱
# 4, 5
a[1,:2]

array([4, 5])

In [10]:
# 2,3,5,6
a[:, 1:]

array([[2, 3],
       [5, 6]])

In [11]:
# 1,4,3,6
a[:, ::2] # 첨부터 끝까지 스텝 2개씩 준당

array([[1, 3],
       [4, 6]])

- Array 생성

In [12]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [13]:
# 실수 사용 가능
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [14]:
# 오름차순(ascending order)
np.sort(a)

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
# 내림차순 (descending order)
np.sort(a)[::-1]


array([[4, 5, 6],
       [1, 2, 3]])

In [ ]:
# 참고 사항 - palindrome
# check whether a string is a palindrome
def is_palindrome(s):       # s가 palindrome이면 true, 아니면 false를 반환하는 함수
    return s == s[::-1]

In [17]:
index = np.argsort(a) # argsort: # [2,3,1,0]
a[index]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [ ]:
# fancy indexing
a[[2,3,1,0]]